import type { IChampion } from '@/type/championsCard.type';

export const CHAMPIONS: IChampion[] = [
  {
    id: 1,
    name: 'Гарен',
    gender: 'мужской',
    race: 'человек',
    lanes: ['топ'],
    regions: ['Демасия', 'Ноксус'],
    resource: 'без ресурса',
    attackType: 'ближний',
    releaseYear: 2010,
    image:
      'https://ddragon.leagueoflegends.com/cdn/img/champion/tiles/Garen_0.jpg',
  },
  {
    id: 2,
    name: 'Дариус',
    gender: 'мужской',
    race: 'человек',
    lanes: ['топ'],
    regions: ['Ноксус'],
    resource: 'мана',
    attackType: 'ближний',
    releaseYear: 2012,
    image:
      'https://ddragon.leagueoflegends.com/cdn/img/champion/tiles/Darius_0.jpg',
  },
  {
    id: 3,
    name: 'Фиора',
    gender: 'женский',
    race: 'человек',
    lanes: ['топ'],
    regions: ['Демасия'],
    resource: 'мана',
    attackType: 'ближний',
    releaseYear: 2015,
    image:
      'https://ddragon.leagueoflegends.com/cdn/img/champion/tiles/Fiora_0.jpg',
  },
  {
    id: 4,
    name: 'Аатрокс',
    gender: 'мужской',
    race: 'даркин',
    lanes: ['топ'],
    regions: ['Шурима'],
    resource: 'кровь',
    attackType: 'ближний',
    releaseYear: 2013,
    image:
      'https://ddragon.leagueoflegends.com/cdn/img/champion/tiles/Aatrox_0.jpg',
  },
  {
    id: 5,
    name: 'Ли Син',
    gender: 'мужской',
    race: 'человек',
    lanes: ['лес'],
    regions: ['Иония'],
    resource: 'энергия',
    attackType: 'ближний',
    releaseYear: 2011,
    image:
      'https://ddragon.leagueoflegends.com/cdn/img/champion/tiles/LeeSin_0.jpg',
  },
  {
    id: 6,
    name: "Кха'Зикс",
    gender: 'мужской',
    race: 'бездна',
    lanes: ['лес'],
    regions: ['Бездна'],
    resource: 'мана',
    attackType: 'ближний',
    releaseYear: 2012,
    image:
      'https://ddragon.leagueoflegends.com/cdn/img/champion/tiles/Khazix_0.jpg',
  },
  {
    id: 7,
    name: 'Элиза',
    gender: 'женский',
    race: 'человек',
    lanes: ['лес'],
    regions: ['Ноксус', 'Острова'],
    resource: 'мана',
    attackType: ['дальний', 'ближний'],
    releaseYear: 2012,
    image:
      'https://ddragon.leagueoflegends.com/cdn/img/champion/tiles/Elise_0.jpg',
  },
  {
    id: 8,
    name: 'Вай',
    gender: 'женский',
    race: 'человек',
    lanes: ['лес'],
    regions: ['Пилтовер', 'Заун'],
    resource: 'мана',
    attackType: 'ближний',
    releaseYear: 2012,
    image:
      'https://ddragon.leagueoflegends.com/cdn/img/champion/tiles/Vi_0.jpg',
  },
  {
    id: 9,
    name: 'Ари',
    gender: 'женский',
    race: 'вастайя',
    lanes: ['мид'],
    regions: ['Иония'],
    resource: 'мана',
    attackType: 'дальний',
    releaseYear: 2011,
    image:
      'https://ddragon.leagueoflegends.com/cdn/img/champion/tiles/Ahri_0.jpg',
  },
  {
    id: 10,
    name: 'Зед',
    gender: 'мужской',
    race: 'человек',
    lanes: ['мид'],
    regions: ['Иония'],
    resource: 'энергия',
    attackType: 'ближний',
    releaseYear: 2012,
    image:
      'https://ddragon.leagueoflegends.com/cdn/img/champion/tiles/Zed_0.jpg',
  },
  {
    id: 11,
    name: 'Люкс',
    gender: 'женский',
    race: 'человек',
    lanes: ['мид', 'саппорт'],
    regions: ['Демасия'],
    resource: 'мана',
    attackType: 'дальний',
    releaseYear: 2010,
    image:
      'https://ddragon.leagueoflegends.com/cdn/img/champion/tiles/Lux_0.jpg',
  },
  {
    id: 12,
    name: 'Катарина',
    gender: 'женский',
    race: 'человек',
    lanes: ['мид'],
    regions: ['Ноксус'],
    resource: 'без ресурса',
    attackType: 'ближний',
    releaseYear: 2009,
    image:
      'https://ddragon.leagueoflegends.com/cdn/img/champion/tiles/Katarina_0.jpg',
  },
  {
    id: 13,
    name: 'Эш',
    gender: 'женский',
    race: 'человек',
    lanes: ['адк'],
    regions: ['Фрельйорд'],
    resource: 'мана',
    attackType: 'дальний',
    releaseYear: 2009,
    image:
      'https://ddragon.leagueoflegends.com/cdn/img/champion/tiles/Ashe_0.jpg',
  },
  {
    id: 14,
    name: 'Джинкс',
    gender: 'женский',
    race: 'человек',
    lanes: ['адк'],
    regions: ['Заун'],
    resource: 'мана',
    attackType: 'дальний',
    releaseYear: 2013,
    image:
      'https://ddragon.leagueoflegends.com/cdn/img/champion/tiles/Jinx_0.jpg',
  },
  {
    id: 15,
    name: 'Кейтлин',
    gender: 'женский',
    race: 'человек',
    lanes: ['адк'],
    regions: ['Пилтовер'],
    resource: 'мана',
    attackType: 'дальний',
    releaseYear: 2011,
    image:
      'https://ddragon.leagueoflegends.com/cdn/img/champion/tiles/Caitlyn_0.jpg',
  },
  {
    id: 16,
    name: 'Вейн',
    gender: 'женский',
    race: 'человек',
    lanes: ['адк', 'топ'],
    regions: ['Демасия'],
    resource: 'мана',
    attackType: 'дальний',
    releaseYear: 2011,
    image:
      'https://ddragon.leagueoflegends.com/cdn/img/champion/tiles/Vayne_0.jpg',
  },
  {
    id: 17,
    name: 'Треш',
    gender: 'мужской',
    race: 'призрак',
    lanes: ['саппорт'],
    regions: ['Острова'],
    resource: 'мана',
    attackType: 'ближний',
    releaseYear: 2013,
    image:
      'https://ddragon.leagueoflegends.com/cdn/img/champion/tiles/Thresh_0.jpg',
  },
  {
    id: 18,
    name: 'Леона',
    gender: 'женский',
    race: 'человек',
    lanes: ['саппорт'],
    regions: ['Таргон'],
    resource: 'мана',
    attackType: 'ближний',
    releaseYear: 2011,
    image:
      'https://ddragon.leagueoflegends.com/cdn/img/champion/tiles/Leona_0.jpg',
  },
  {
    id: 19,
    name: 'Сорака',
    gender: 'женский',
    race: 'сущность',
    lanes: ['саппорт'],
    regions: ['Таргон'],
    resource: 'мана',
    attackType: 'дальний',
    releaseYear: 2009,
    image:
      'https://ddragon.leagueoflegends.com/cdn/img/champion/tiles/Soraka_0.jpg',
  },
  {
    id: 20,
    name: 'Нами',
    gender: 'женский',
    race: 'вастайя',
    lanes: ['саппорт'],
    regions: ['Иония'],
    resource: 'мана',
    attackType: 'дальний',
    releaseYear: 2012,
    image:
      'https://ddragon.leagueoflegends.com/cdn/img/champion/tiles/Nami_0.jpg',
  },
  {
    id: 21,
    name: 'Энни',
    gender: 'женский',
    race: 'человек',
    lanes: ['мид', 'саппорт'],
    regions: ['Ноксус'],
    resource: 'мана',
    attackType: 'дальний',
    releaseYear: 2009,
    image:
      'https://ddragon.leagueoflegends.com/cdn/img/champion/tiles/Annie_0.jpg',
  },
  {
    id: 22,
    name: 'Олаф',
    gender: 'мужской',
    race: 'человек',
    lanes: ['топ', 'лес'],
    regions: ['Фрельйорд'],
    resource: 'мана',
    attackType: 'ближний',
    releaseYear: 2010,
    image:
      'https://ddragon.leagueoflegends.com/cdn/img/champion/tiles/Olaf_0.jpg',
  },
  {
    id: 23,
    name: 'Галио',
    gender: 'мужской',
    race: 'голем',
    lanes: ['мид', 'саппорт'],
    regions: ['Демасия'],
    resource: 'мана',
    attackType: 'ближний',
    releaseYear: 2010,
    image:
      'https://ddragon.leagueoflegends.com/cdn/img/champion/tiles/Galio_0.jpg',
  },
  {
    id: 24,
    name: 'Твистед Фэйт',
    gender: 'мужской',
    race: 'человек',
    lanes: ['мид'],
    regions: ['Билджвотер'],
    resource: 'мана',
    attackType: 'дальний',
    releaseYear: 2009,
    image:
      'https://ddragon.leagueoflegends.com/cdn/img/champion/tiles/TwistedFate_0.jpg',
  },
  {
    id: 25,
    name: 'Ксин Жао',
    gender: 'мужской',
    race: 'человек',
    lanes: ['лес'],
    regions: ['Демасия', 'Иония'],
    resource: 'мана',
    attackType: 'ближний',
    releaseYear: 2010,
    image:
      'https://ddragon.leagueoflegends.com/cdn/img/champion/tiles/XinZhao_0.jpg',
  },
  {
    id: 26,
    name: 'Ургот',
    gender: 'мужской',
    race: 'человек',
    lanes: ['топ'],
    regions: ['Ноксус', 'Заун'],
    resource: 'мана',
    attackType: 'дальний',
    releaseYear: 2010,
    image:
      'https://ddragon.leagueoflegends.com/cdn/img/champion/tiles/Urgot_0.jpg',
  },
  {
    id: 27,
    name: 'Ле Блан',
    gender: 'женский',
    race: 'человек',
    lanes: ['мид'],
    regions: ['Ноксус'],
    resource: 'мана',
    attackType: 'дальний',
    releaseYear: 2010,
    image:
      'https://ddragon.leagueoflegends.com/cdn/img/champion/tiles/Leblanc_0.jpg',
  },
  {
    id: 28,
    name: 'Владимир',
    gender: 'мужской',
    race: 'человек',
    lanes: ['топ', 'мид'],
    regions: ['Ноксус'],
    resource: 'кровь',
    attackType: 'дальний',
    releaseYear: 2010,
    image:
      'https://ddragon.leagueoflegends.com/cdn/img/champion/tiles/Vladimir_0.jpg',
  },
  {
    id: 29,
    name: 'Фиддлстикс',
    gender: 'мужской',
    race: 'демон',
    lanes: ['лес', 'саппорт'],
    regions: ['Рунтерра'],
    resource: 'мана',
    attackType: 'дальний',
    releaseYear: 2009,
    image:
      'https://ddragon.leagueoflegends.com/cdn/img/champion/tiles/FiddleSticks_0.jpg',
  },
  {
    id: 30,
    name: 'Кейл',
    gender: 'женский',
    race: 'сущность',
    lanes: ['топ'],
    regions: ['Демасия', 'Таргон'],
    resource: 'мана',
    attackType: ['ближний', 'дальний'],
    releaseYear: 2009,
    image:
      'https://ddragon.leagueoflegends.com/cdn/img/champion/tiles/Kayle_0.jpg',
  },
  {
    id: 31,
    name: 'Мастер Йи',
    gender: 'мужской',
    race: 'человек',
    lanes: ['лес'],
    regions: ['Иония'],
    resource: 'мана',
    attackType: 'ближний',
    releaseYear: 2009,
    image:
      'https://ddragon.leagueoflegends.com/cdn/img/champion/tiles/MasterYi_0.jpg',
  },
  {
    id: 32,
    name: 'Алистар',
    gender: 'мужской',
    race: 'минотавр',
    lanes: ['саппорт'],
    regions: ['Рунтерра'],
    resource: 'мана',
    attackType: 'ближний',
    releaseYear: 2009,
    image:
      'https://ddragon.leagueoflegends.com/cdn/img/champion/tiles/Alistar_0.jpg',
  },
  {
    id: 33,
    name: 'Райз',
    gender: 'мужской',
    race: 'человек',
    lanes: ['мид'],
    regions: ['Рунтерра'],
    resource: 'мана',
    attackType: 'дальний',
    releaseYear: 2009,
    image:
      'https://ddragon.leagueoflegends.com/cdn/img/champion/tiles/Ryze_0.jpg',
  },
  {
    id: 34,
    name: 'Сион',
    gender: 'мужской',
    race: 'нежить',
    lanes: ['топ'],
    regions: ['Ноксус'],
    resource: 'мана',
    attackType: 'ближний',
    releaseYear: 2009,
    image:
      'https://ddragon.leagueoflegends.com/cdn/img/champion/tiles/Sion_0.jpg',
  },
  {
    id: 35,
    name: 'Сивир',
    gender: 'женский',
    race: 'человек',
    lanes: ['адк'],
    regions: ['Шурима'],
    resource: 'мана',
    attackType: 'дальний',
    releaseYear: 2009,
    image:
      'https://ddragon.leagueoflegends.com/cdn/img/champion/tiles/Sivir_0.jpg',
  },
  {
    id: 36,
    name: 'Тимо',
    gender: 'мужской',
    race: 'йордл',
    lanes: ['топ'],
    regions: ['Бандл Сити'],
    resource: 'мана',
    attackType: 'дальний',
    releaseYear: 2009,
    image:
      'https://ddragon.leagueoflegends.com/cdn/img/champion/tiles/Teemo_0.jpg',
  },
  {
    id: 37,
    name: 'Тристана',
    gender: 'женский',
    race: 'йордл',
    lanes: ['адк'],
    regions: ['Бандл Сити'],
    resource: 'мана',
    attackType: 'дальний',
    releaseYear: 2009,
    image:
      'https://ddragon.leagueoflegends.com/cdn/img/champion/tiles/Tristana_0.jpg',
  },
  {
    id: 38,
    name: 'Варвик',
    gender: 'мужской',
    race: 'человек',
    lanes: ['лес'],
    regions: ['Заун'],
    resource: 'мана',
    attackType: 'ближний',
    releaseYear: 2009,
    image:
      'https://ddragon.leagueoflegends.com/cdn/img/champion/tiles/Warwick_0.jpg',
  },
  {
    id: 39,
    name: 'Нуну и Виллумп',
    gender: 'мужской',
    race: ['человек', 'йети'],
    lanes: ['лес'],
    regions: ['Фрельйорд'],
    resource: 'мана',
    attackType: 'ближний',
    releaseYear: 2009,
    image:
      'https://ddragon.leagueoflegends.com/cdn/img/champion/tiles/Nunu_0.jpg',
  },
  {
    id: 40,
    name: 'Мисс Фортуна',
    gender: 'женский',
    race: 'человек',
    lanes: ['адк'],
    regions: ['Билджвотер'],
    resource: 'мана',
    attackType: 'дальний',
    releaseYear: 2010,
    image:
      'https://ddragon.leagueoflegends.com/cdn/img/champion/tiles/MissFortune_0.jpg',
  },
  {
    id: 41,
    name: 'Триндамир',
    gender: 'мужской',
    race: 'человек',
    lanes: ['топ'],
    regions: ['Фрельйорд'],
    resource: 'ярость',
    attackType: 'ближний',
    releaseYear: 2009,
    image:
      'https://ddragon.leagueoflegends.com/cdn/img/champion/tiles/Tryndamere_0.jpg',
  },
  {
    id: 42,
    name: 'Джакс',
    gender: 'мужской',
    race: 'неизвестно',
    lanes: ['топ', 'лес'],
    regions: ['Икатия'],
    resource: 'мана',
    attackType: 'ближний',
    releaseYear: 2009,
    image:
      'https://ddragon.leagueoflegends.com/cdn/img/champion/tiles/Jax_0.jpg',
  },
  {
    id: 43,
    name: 'Моргана',
    gender: 'женский',
    race: 'сущность',
    lanes: ['саппорт', 'мид'],
    regions: ['Демасия', 'Таргон'],
    resource: 'мана',
    attackType: 'дальний',
    releaseYear: 2009,
    image:
      'https://ddragon.leagueoflegends.com/cdn/img/champion/tiles/Morgana_0.jpg',
  },
  {
    id: 44,
    name: 'Зилеан',
    gender: 'мужской',
    race: 'человек',
    lanes: ['саппорт', 'мид'],
    regions: ['Икатия'],
    resource: 'мана',
    attackType: 'дальний',
    releaseYear: 2009,
    image:
      'https://ddragon.leagueoflegends.com/cdn/img/champion/tiles/Zilean_0.jpg',
  },
  {
    id: 45,
    name: 'Синджед',
    gender: 'мужской',
    race: 'человек',
    lanes: ['топ'],
    regions: ['Заун'],
    resource: 'мана',
    attackType: 'ближний',
    releaseYear: 2009,
    image:
      'https://ddragon.leagueoflegends.com/cdn/img/champion/tiles/Singed_0.jpg',
  },
  {
    id: 46,
    name: 'Эвелинн',
    gender: 'женский',
    race: 'демон',
    lanes: ['лес'],
    regions: ['Рунтерра'],
    resource: 'мана',
    attackType: 'ближний',
    releaseYear: 2009,
    image:
      'https://ddragon.leagueoflegends.com/cdn/img/champion/tiles/Evelynn_0.jpg',
  },
  {
    id: 47,
    name: 'Твич',
    gender: 'мужской',
    race: 'крыса',
    lanes: ['адк', 'лес'],
    regions: ['Заун'],
    resource: 'мана',
    attackType: 'дальний',
    releaseYear: 2009,
    image:
      'https://ddragon.leagueoflegends.com/cdn/img/champion/tiles/Twitch_0.jpg',
  },
  {
    id: 48,
    name: 'Картус',
    gender: 'мужской',
    race: 'нежить',
    lanes: ['мид', 'лес'],
    regions: ['Острова'],
    resource: 'мана',
    attackType: 'дальний',
    releaseYear: 2009,
    image:
      'https://ddragon.leagueoflegends.com/cdn/img/champion/tiles/Karthus_0.jpg',
  },
  {
    id: 49,
    name: "Чо'Гат",
    gender: 'мужской',
    race: 'бездна',
    lanes: ['топ', 'мид'],
    regions: ['Бездна'],
    resource: 'мана',
    attackType: 'ближний',
    releaseYear: 2009,
    image:
      'https://ddragon.leagueoflegends.com/cdn/img/champion/tiles/Chogath_0.jpg',
  },
  {
    id: 50,
    name: 'Амуму',
    gender: 'мужской',
    race: 'нежить',
    lanes: ['лес'],
    regions: ['Шурима'],
    resource: 'мана',
    attackType: 'ближний',
    releaseYear: 2009,
    image:
      'https://ddragon.leagueoflegends.com/cdn/img/champion/tiles/Amumu_0.jpg',
  },
  {
    id: 51,
    name: 'Раммус',
    gender: 'мужской',
    race: 'броненосец',
    lanes: ['лес'],
    regions: ['Шурима'],
    resource: 'мана',
    attackType: 'ближний',
    releaseYear: 2009,
    image:
      'https://ddragon.leagueoflegends.com/cdn/img/champion/tiles/Rammus_0.jpg',
  },
  {
    id: 52,
    name: 'Анивия',
    gender: 'женский',
    race: 'дух',
    lanes: ['мид'],
    regions: ['Фрельйорд'],
    resource: 'мана',
    attackType: 'дальний',
    releaseYear: 2009,
    image:
      'https://ddragon.leagueoflegends.com/cdn/img/champion/tiles/Anivia_0.jpg',
  },
  {
    id: 53,
    name: 'Шако',
    gender: 'мужской',
    race: 'демон',
    lanes: ['лес', 'саппорт'],
    regions: ['Рунтерра'],
    resource: 'мана',
    attackType: 'ближний',
    releaseYear: 2009,
    image:
      'https://ddragon.leagueoflegends.com/cdn/img/champion/tiles/Shaco_0.jpg',
  },
  {
    id: 54,
    name: 'Доктор Мундо',
    gender: 'мужской',
    race: 'человек',
    lanes: ['топ', 'лес'],
    regions: ['Заун'],
    resource: 'без ресурса',
    attackType: 'ближний',
    releaseYear: 2009,
    image:
      'https://ddragon.leagueoflegends.com/cdn/img/champion/tiles/DrMundo_0.jpg',
  },
  {
    id: 55,
    name: 'Сона',
    gender: 'женский',
    race: 'человек',
    lanes: ['саппорт'],
    regions: ['Демасия', 'Иония'],
    resource: 'мана',
    attackType: 'дальний',
    releaseYear: 2010,
    image:
      'https://ddragon.leagueoflegends.com/cdn/img/champion/tiles/Sona_0.jpg',
  },
  {
    id: 56,
    name: 'Кассадин',
    gender: 'мужской',
    race: 'человек',
    lanes: ['мид'],
    regions: ['Шурима', 'Бездна'],
    resource: 'мана',
    attackType: 'ближний',
    releaseYear: 2009,
    image:
      'https://ddragon.leagueoflegends.com/cdn/img/champion/tiles/Kassadin_0.jpg',
  },
  {
    id: 57,
    name: 'Ирелия',
    gender: 'женский',
    race: 'человек',
    lanes: ['топ', 'мид'],
    regions: ['Иония'],
    resource: 'мана',
    attackType: 'ближний',
    releaseYear: 2010,
    image:
      'https://ddragon.leagueoflegends.com/cdn/img/champion/tiles/Irelia_0.jpg',
  },
  {
    id: 58,
    name: 'Жанна',
    gender: 'женский',
    race: 'дух',
    lanes: ['саппорт'],
    regions: ['Заун', 'Шурима'],
    resource: 'мана',
    attackType: 'дальний',
    releaseYear: 2009,
    image:
      'https://ddragon.leagueoflegends.com/cdn/img/champion/tiles/Janna_0.jpg',
  },
  {
    id: 59,
    name: 'Гангпланк',
    gender: 'мужской',
    race: 'человек',
    lanes: ['топ'],
    regions: ['Билджвотер'],
    resource: 'мана',
    attackType: 'ближний',
    releaseYear: 2009,
    image:
      'https://ddragon.leagueoflegends.com/cdn/img/champion/tiles/Gangplank_0.jpg',
  },
  {
    id: 60,
    name: 'Корки',
    gender: 'мужской',
    race: 'йордл',
    lanes: ['мид', 'адк'],
    regions: ['Бандл Сити', 'Пилтовер'],
    resource: 'мана',
    attackType: 'дальний',
    releaseYear: 2009,
    image:
      'https://ddragon.leagueoflegends.com/cdn/img/champion/tiles/Corki_0.jpg',
  },
  {
    id: 61,
    name: 'Карма',
    gender: 'женский',
    race: 'человек',
    lanes: ['саппорт', 'мид'],
    regions: ['Иония'],
    resource: 'мана',
    attackType: 'дальний',
    releaseYear: 2011,
    image:
      'https://ddragon.leagueoflegends.com/cdn/img/champion/tiles/Karma_0.jpg',
  },
  {
    id: 62,
    name: 'Тарик',
    gender: 'мужской',
    race: 'сущность',
    lanes: ['саппорт'],
    regions: ['Демасия', 'Таргон'],
    resource: 'мана',
    attackType: 'ближний',
    releaseYear: 2009,
    image:
      'https://ddragon.leagueoflegends.com/cdn/img/champion/tiles/Taric_0.jpg',
  },
  {
    id: 63,
    name: 'Вейгар',
    gender: 'мужской',
    race: 'йордл',
    lanes: ['мид'],
    regions: ['Бандл Сити'],
    resource: 'мана',
    attackType: 'дальний',
    releaseYear: 2009,
    image:
      'https://ddragon.leagueoflegends.com/cdn/img/champion/tiles/Veigar_0.jpg',
  },
  {
    id: 64,
    name: 'Трандл',
    gender: 'мужской',
    race: 'тролль',
    lanes: ['топ', 'лес'],
    regions: ['Фрельйорд'],
    resource: 'мана',
    attackType: 'ближний',
    releaseYear: 2010,
    image:
      'https://ddragon.leagueoflegends.com/cdn/img/champion/tiles/Trundle_0.jpg',
  },
  {
    id: 65,
    name: 'Свейн',
    gender: 'мужской',
    race: 'человек',
    lanes: ['мид', 'саппорт'],
    regions: ['Ноксус'],
    resource: 'мана',
    attackType: 'дальний',
    releaseYear: 2010,
    image:
      'https://ddragon.leagueoflegends.com/cdn/img/champion/tiles/Swain_0.jpg',
  },
  {
    id: 66,
    name: 'Блицкранк',
    gender: 'мужской',
    race: 'голем',
    lanes: ['саппорт'],
    regions: ['Заун'],
    resource: 'мана',
    attackType: 'ближний',
    releaseYear: 2009,
    image:
      'https://ddragon.leagueoflegends.com/cdn/img/champion/tiles/Blitzcrank_0.jpg',
  },
  {
    id: 67,
    name: 'Мальфит',
    gender: 'мужской',
    race: 'голем',
    lanes: ['топ', 'мид'],
    regions: ['Иксталь'],
    resource: 'мана',
    attackType: 'ближний',
    releaseYear: 2009,
    image:
      'https://ddragon.leagueoflegends.com/cdn/img/champion/tiles/Malphite_0.jpg',
  },
  {
    id: 68,
    name: 'Ноктюрн',
    gender: 'мужской',
    race: 'демон',
    lanes: ['лес'],
    regions: ['Рунтерра'],
    resource: 'мана',
    attackType: 'ближний',
    releaseYear: 2011,
    image:
      'https://ddragon.leagueoflegends.com/cdn/img/champion/tiles/Nocturne_0.jpg',
  },
  {
    id: 69,
    name: 'Маокай',
    gender: 'мужской',
    race: 'дух',
    lanes: ['топ', 'саппорт', 'лес'],
    regions: ['Острова'],
    resource: 'мана',
    attackType: 'ближний',
    releaseYear: 2011,
    image:
      'https://ddragon.leagueoflegends.com/cdn/img/champion/tiles/Maokai_0.jpg',
  },
  {
    id: 70,
    name: 'Ренектон',
    gender: 'мужской',
    race: 'вознесшийся',
    lanes: ['топ'],
    regions: ['Шурима'],
    resource: 'ярость',
    attackType: 'ближний',
    releaseYear: 2011,
    image:
      'https://ddragon.leagueoflegends.com/cdn/img/champion/tiles/Renekton_0.jpg',
  },
  {
    id: 71,
    name: 'Джарван IV',
    gender: 'мужской',
    race: 'человек',
    lanes: ['лес', 'топ'],
    regions: ['Демасия'],
    resource: 'мана',
    attackType: 'ближний',
    releaseYear: 2011,
    image:
      'https://ddragon.leagueoflegends.com/cdn/img/champion/tiles/JarvanIV_0.jpg',
  },
  {
    id: 72,
    name: 'Орианна',
    gender: 'женский',
    race: 'машина',
    lanes: ['мид'],
    regions: ['Пилтовер', 'Заун'],
    resource: 'мана',
    attackType: 'дальний',
    releaseYear: 2011,
    image:
      'https://ddragon.leagueoflegends.com/cdn/img/champion/tiles/Orianna_0.jpg',
  },
  {
    id: 73,
    name: 'Вуконг',
    gender: 'мужской',
    race: 'вастайя',
    lanes: ['топ', 'лес'],
    regions: ['Иония'],
    resource: 'мана',
    attackType: 'ближний',
    releaseYear: 2011,
    image:
      'https://ddragon.leagueoflegends.com/cdn/img/champion/tiles/MonkeyKing_0.jpg',
  },
  {
    id: 74,
    name: 'Брэнд',
    gender: 'мужской',
    race: 'человек',
    lanes: ['мид', 'саппорт'],
    regions: ['Фрельйорд', 'Рунтерра'],
    resource: 'мана',
    attackType: 'дальний',
    releaseYear: 2011,
    image:
      'https://ddragon.leagueoflegends.com/cdn/img/champion/tiles/Brand_0.jpg',
  },
  {
    id: 75,
    name: 'Рамбл',
    gender: 'мужской',
    race: 'йордл',
    lanes: ['топ', 'мид'],
    regions: ['Бандл Сити'],
    resource: 'тепло',
    attackType: 'ближний',
    releaseYear: 2011,
    image:
      'https://ddragon.leagueoflegends.com/cdn/img/champion/tiles/Rumble_0.jpg',
  },
  {
    id: 76,
    name: 'Кассиопея',
    gender: 'женский',
    race: 'человек',
    lanes: ['мид'],
    regions: ['Ноксус', 'Шурима'],
    resource: 'мана',
    attackType: 'дальний',
    releaseYear: 2010,
    image:
      'https://ddragon.leagueoflegends.com/cdn/img/champion/tiles/Cassiopeia_0.jpg',
  },
  {
    id: 77,
    name: 'Скарнер',
    gender: 'мужской',
    race: 'бракерн',
    lanes: ['лес', 'топ'],
    regions: ['Иксталь'],
    resource: 'мана',
    attackType: 'ближний',
    releaseYear: 2011,
    image:
      'https://ddragon.leagueoflegends.com/cdn/img/champion/tiles/Skarner_0.jpg',
  },
  {
    id: 78,
    name: 'Хеймердингер',
    gender: 'мужской',
    race: 'йордл',
    lanes: ['мид', 'топ', 'саппорт'],
    regions: ['Бандл Сити', 'Пилтовер'],
    resource: 'мана',
    attackType: 'дальний',
    releaseYear: 2009,
    image:
      'https://ddragon.leagueoflegends.com/cdn/img/champion/tiles/Heimerdinger_0.jpg',
  },
  {
    id: 79,
    name: 'Насус',
    gender: 'мужской',
    race: 'вознесшийся',
    lanes: ['топ'],
    regions: ['Шурима'],
    resource: 'мана',
    attackType: 'ближний',
    releaseYear: 2009,
    image:
      'https://ddragon.leagueoflegends.com/cdn/img/champion/tiles/Nasus_0.jpg',
  },
  {
    id: 80,
    name: 'Нидали',
    gender: 'женский',
    race: 'человек',
    lanes: ['лес', 'топ'],
    regions: ['Иксталь'],
    resource: 'мана',
    attackType: ['дальний', 'ближний'],
    releaseYear: 2009,
    image:
      'https://ddragon.leagueoflegends.com/cdn/img/champion/tiles/Nidalee_0.jpg',
  },
  {
    id: 81,
    name: 'Удир',
    gender: 'мужской',
    race: 'человек',
    lanes: ['лес', 'топ'],
    regions: ['Фрельйорд', 'Иония'],
    resource: 'мана',
    attackType: 'ближний',
    releaseYear: 2009,
    image:
      'https://ddragon.leagueoflegends.com/cdn/img/champion/tiles/Udyr_0.jpg',
  },
  {
    id: 82,
    name: 'Поппи',
    gender: 'женский',
    race: 'йордл',
    lanes: ['топ', 'лес', 'саппорт'],
    regions: ['Демасия', 'Бандл Сити'],
    resource: 'мана',
    attackType: 'ближний',
    releaseYear: 2010,
    image:
      'https://ddragon.leagueoflegends.com/cdn/img/champion/tiles/Poppy_0.jpg',
  },
  {
    id: 83,
    name: 'Грагас',
    gender: 'мужской',
    race: 'человек',
    lanes: ['лес', 'топ', 'мид'],
    regions: ['Фрельйорд'],
    resource: 'мана',
    attackType: 'ближний',
    releaseYear: 2010,
    image:
      'https://ddragon.leagueoflegends.com/cdn/img/champion/tiles/Gragas_0.jpg',
  },
  {
    id: 84,
    name: 'Пантеон',
    gender: 'мужской',
    race: 'человек',
    lanes: ['топ', 'саппорт', 'мид'],
    regions: ['Таргон'],
    resource: 'мана',
    attackType: 'ближний',
    releaseYear: 2010,
    image:
      'https://ddragon.leagueoflegends.com/cdn/img/champion/tiles/Pantheon_0.jpg',
  },
  {
    id: 85,
    name: 'Эзреаль',
    gender: 'мужской',
    race: 'человек',
    lanes: ['адк', 'мид'],
    regions: ['Пилтовер'],
    resource: 'мана',
    attackType: 'дальний',
    releaseYear: 2010,
    image:
      'https://ddragon.leagueoflegends.com/cdn/img/champion/tiles/Ezreal_0.jpg',
  },
  {
    id: 86,
    name: 'Мордекайзер',
    gender: 'мужской',
    race: 'нежить',
    lanes: ['топ'],
    regions: ['Ноксус'],
    resource: 'без ресурса',
    attackType: 'ближний',
    releaseYear: 2010,
    image:
      'https://ddragon.leagueoflegends.com/cdn/img/champion/tiles/Mordekaiser_0.jpg',
  },
  {
    id: 87,
    name: 'Йорик',
    gender: 'мужской',
    race: 'человек',
    lanes: ['топ'],
    regions: ['Острова'],
    resource: 'мана',
    attackType: 'ближний',
    releaseYear: 2011,
    image:
      'https://ddragon.leagueoflegends.com/cdn/img/champion/tiles/Yorick_0.jpg',
  },
  {
    id: 88,
    name: 'Акали',
    gender: 'женский',
    race: 'человек',
    lanes: ['мид', 'топ'],
    regions: ['Иония'],
    resource: 'энергия',
    attackType: 'ближний',
    releaseYear: 2010,
    image:
      'https://ddragon.leagueoflegends.com/cdn/img/champion/tiles/Akali_0.jpg',
  },
  {
    id: 89,
    name: 'Кеннен',
    gender: 'мужской',
    race: 'йордл',
    lanes: ['топ', 'мид'],
    regions: ['Иония', 'Бандл Сити'],
    resource: 'энергия',
    attackType: 'дальний',
    releaseYear: 2010,
    image:
      'https://ddragon.leagueoflegends.com/cdn/img/champion/tiles/Kennen_0.jpg',
  },
  {
    id: 90,
    name: 'Мальзахар',
    gender: 'мужской',
    race: 'человек',
    lanes: ['мид'],
    regions: ['Шурима', 'Бездна'],
    resource: 'мана',
    attackType: 'дальний',
    releaseYear: 2010,
    image:
      'https://ddragon.leagueoflegends.com/cdn/img/champion/tiles/Malzahar_0.jpg',
  },
  {
    id: 91,
    name: 'Талон',
    gender: 'мужской',
    race: 'человек',
    lanes: ['мид', 'лес'],
    regions: ['Ноксус'],
    resource: 'мана',
    attackType: 'ближний',
    releaseYear: 2011,
    image:
      'https://ddragon.leagueoflegends.com/cdn/img/champion/tiles/Talon_0.jpg',
  },
  {
    id: 92,
    name: 'Ривен',
    gender: 'женский',
    race: 'человек',
    lanes: ['топ'],
    regions: ['Ноксус', 'Иония'],
    resource: 'без ресурса',
    attackType: 'ближний',
    releaseYear: 2011,
    image:
      'https://ddragon.leagueoflegends.com/cdn/img/champion/tiles/Riven_0.jpg',
  },
  {
    id: 93,
    name: "Ког'Мао",
    gender: 'мужской',
    race: 'бездна',
    lanes: ['адк', 'мид'],
    regions: ['Бездна'],
    resource: 'мана',
    attackType: 'дальний',
    releaseYear: 2010,
    image:
      'https://ddragon.leagueoflegends.com/cdn/img/champion/tiles/KogMaw_0.jpg',
  },
  {
    id: 94,
    name: 'Шен',
    gender: 'мужской',
    race: 'человек',
    lanes: ['топ', 'саппорт'],
    regions: ['Иония'],
    resource: 'энергия',
    attackType: 'ближний',
    releaseYear: 2010,
    image:
      'https://ddragon.leagueoflegends.com/cdn/img/champion/tiles/Shen_0.jpg',
  },
  {
    id: 95,
    name: 'Ксерат',
    gender: 'мужской',
    race: 'вознесшийся',
    lanes: ['мид', 'саппорт'],
    regions: ['Шурима'],
    resource: 'мана',
    attackType: 'дальний',
    releaseYear: 2011,
    image:
      'https://ddragon.leagueoflegends.com/cdn/img/champion/tiles/Xerath_0.jpg',
  },
  {
    id: 96,
    name: 'Шивана',
    gender: 'женский',
    race: 'дракон',
    lanes: ['лес', 'топ'],
    regions: ['Демасия'],
    resource: 'ярость',
    attackType: 'ближний',
    releaseYear: 2011,
    image:
      'https://ddragon.leagueoflegends.com/cdn/img/champion/tiles/Shyvana_0.jpg',
  },
  {
    id: 97,
    name: 'Грейвз',
    gender: 'мужской',
    race: 'человек',
    lanes: ['лес'],
    regions: ['Билджвотер'],
    resource: 'мана',
    attackType: 'дальний',
    releaseYear: 2011,
    image:
      'https://ddragon.leagueoflegends.com/cdn/img/champion/tiles/Graves_0.jpg',
  },
  {
    id: 98,
    name: 'Физз',
    gender: 'мужской',
    race: 'йордл',
    lanes: ['мид'],
    regions: ['Билджвотер'],
    resource: 'мана',
    attackType: 'ближний',
    releaseYear: 2011,
    image:
      'https://ddragon.leagueoflegends.com/cdn/img/champion/tiles/Fizz_0.jpg',
  },
  {
    id: 99,
    name: 'Волибир',
    gender: 'мужской',
    race: 'дух',
    lanes: ['топ', 'лес'],
    regions: ['Фрельйорд'],
    resource: 'мана',
    attackType: 'ближний',
    releaseYear: 2011,
    image:
      'https://ddragon.leagueoflegends.com/cdn/img/champion/tiles/Volibear_0.jpg',
  },
  {
    id: 100,
    name: 'Ренгар',
    gender: 'мужской',
    race: 'вастайя',
    lanes: ['лес', 'топ'],
    regions: ['Иксталь'],
    resource: 'ярость',
    attackType: 'ближний',
    releaseYear: 2012,
    image:
      'https://ddragon.leagueoflegends.com/cdn/img/champion/tiles/Rengar_0.jpg',
  },
  {
    id: 101,
    name: 'Варус',
    gender: 'мужской',
    race: 'даркин',
    lanes: ['адк', 'мид'],
    regions: ['Иония', 'Шурима'],
    resource: 'мана',
    attackType: 'дальний',
    releaseYear: 2012,
    image:
      'https://ddragon.leagueoflegends.com/cdn/img/champion/tiles/Varus_0.jpg',
  },
  {
    id: 102,
    name: 'Наутилус',
    gender: 'мужской',
    race: 'неизвестно',
    lanes: ['саппорт', 'лес'],
    regions: ['Билджвотер'],
    resource: 'мана',
    attackType: 'ближний',
    releaseYear: 2012,
    image:
      'https://ddragon.leagueoflegends.com/cdn/img/champion/tiles/Nautilus_0.jpg',
  },
  {
    id: 103,
    name: 'Виктор',
    gender: 'мужской',
    race: 'человек',
    lanes: ['мид'],
    regions: ['Заун', 'Пилтовер'],
    resource: 'мана',
    attackType: 'дальний',
    releaseYear: 2011,
    image:
      'https://ddragon.leagueoflegends.com/cdn/img/champion/tiles/Viktor_0.jpg',
  },
  {
    id: 104,
    name: 'Седжуани',
    gender: 'женский',
    race: 'человек',
    lanes: ['лес', 'топ'],
    regions: ['Фрельйорд'],
    resource: 'мана',
    attackType: 'ближний',
    releaseYear: 2012,
    image:
      'https://ddragon.leagueoflegends.com/cdn/img/champion/tiles/Sejuani_0.jpg',
  },
  {
    id: 105,
    name: 'Зиггс',
    gender: 'мужской',
    race: 'йордл',
    lanes: ['мид', 'адк'],
    regions: ['Заун', 'Бандл Сити'],
    resource: 'мана',
    attackType: 'дальний',
    releaseYear: 2012,
    image:
      'https://ddragon.leagueoflegends.com/cdn/img/champion/tiles/Ziggs_0.jpg',
  },
  {
    id: 106,
    name: 'Лулу',
    gender: 'женский',
    race: 'йордл',
    lanes: ['саппорт', 'мид'],
    regions: ['Бандл Сити'],
    resource: 'мана',
    attackType: 'дальний',
    releaseYear: 2012,
    image:
      'https://ddragon.leagueoflegends.com/cdn/img/champion/tiles/Lulu_0.jpg',
  },
  {
    id: 107,
    name: 'Дрейвен',
    gender: 'мужской',
    race: 'человек',
    lanes: ['адк'],
    regions: ['Ноксус'],
    resource: 'мана',
    attackType: 'дальний',
    releaseYear: 2012,
    image:
      'https://ddragon.leagueoflegends.com/cdn/img/champion/tiles/Draven_0.jpg',
  },
  {
    id: 108,
    name: 'Гекарим',
    gender: 'мужской',
    race: 'нежить',
    lanes: ['лес'],
    regions: ['Острова'],
    resource: 'мана',
    attackType: 'ближний',
    releaseYear: 2012,
    image:
      'https://ddragon.leagueoflegends.com/cdn/img/champion/tiles/Hecarim_0.jpg',
  },
  {
    id: 109,
    name: 'Джейс',
    gender: 'мужской',
    race: 'человек',
    lanes: ['топ', 'мид'],
    regions: ['Пилтовер'],
    resource: 'мана',
    attackType: ['дальний', 'ближний'],
    releaseYear: 2012,
    image:
      'https://ddragon.leagueoflegends.com/cdn/img/champion/tiles/Jayce_0.jpg',
  },
  {
    id: 110,
    name: 'Лиссандра',
    gender: 'женский',
    race: 'человек',
    lanes: ['мид', 'топ'],
    regions: ['Фрельйорд'],
    resource: 'мана',
    attackType: 'дальний',
    releaseYear: 2013,
    image:
      'https://ddragon.leagueoflegends.com/cdn/img/champion/tiles/Lissandra_0.jpg',
  },
  {
    id: 111,
    name: 'Диана',
    gender: 'женский',
    race: 'человек',
    lanes: ['мид', 'лес'],
    regions: ['Таргон'],
    resource: 'мана',
    attackType: 'ближний',
    releaseYear: 2012,
    image:
      'https://ddragon.leagueoflegends.com/cdn/img/champion/tiles/Diana_0.jpg',
  },
  {
    id: 112,
    name: 'Зайра',
    gender: 'женский',
    race: 'сущность',
    lanes: ['саппорт', 'мид'],
    regions: ['Иксталь'],
    resource: 'мана',
    attackType: 'дальний',
    releaseYear: 2012,
    image:
      'https://ddragon.leagueoflegends.com/cdn/img/champion/tiles/Zyra_0.jpg',
  },
  {
    id: 113,
    name: 'Синдра',
    gender: 'женский',
    race: 'человек',
    lanes: ['мид'],
    regions: ['Иония'],
    resource: 'мана',
    attackType: 'дальний',
    releaseYear: 2012,
    image:
      'https://ddragon.leagueoflegends.com/cdn/img/champion/tiles/Syndra_0.jpg',
  },
  {
    id: 114,
    name: 'Квинн',
    gender: 'женский',
    race: 'человек',
    lanes: ['топ', 'адк'],
    regions: ['Демасия'],
    resource: 'мана',
    attackType: 'дальний',
    releaseYear: 2013,
    image:
      'https://ddragon.leagueoflegends.com/cdn/img/champion/tiles/Quinn_0.jpg',
  },
  {
    id: 115,
    name: 'Зак',
    gender: 'мужской',
    race: 'сущность',
    lanes: ['лес', 'топ'],
    regions: ['Заун'],
    resource: 'здоровье',
    attackType: 'ближний',
    releaseYear: 2013,
    image:
      'https://ddragon.leagueoflegends.com/cdn/img/champion/tiles/Zac_0.jpg',
  },
  {
    id: 116,
    name: 'Люциан',
    gender: 'мужской',
    race: 'человек',
    lanes: ['адк', 'мид'],
    regions: ['Демасия'],
    resource: 'мана',
    attackType: 'дальний',
    releaseYear: 2013,
    image:
      'https://ddragon.leagueoflegends.com/cdn/img/champion/tiles/Lucian_0.jpg',
  },
  {
    id: 117,
    name: 'Ясуо',
    gender: 'мужской',
    race: 'человек',
    lanes: ['мид', 'топ'],
    regions: ['Иония'],
    resource: 'без ресурса',
    attackType: 'ближний',
    releaseYear: 2013,
    image:
      'https://ddragon.leagueoflegends.com/cdn/img/champion/tiles/Yasuo_0.jpg',
  },
  {
    id: 118,
    name: "Вел'Коз",
    gender: 'мужской',
    race: 'бездна',
    lanes: ['мид', 'саппорт'],
    regions: ['Бездна'],
    resource: 'мана',
    attackType: 'дальний',
    releaseYear: 2014,
    image:
      'https://ddragon.leagueoflegends.com/cdn/img/champion/tiles/Velkoz_0.jpg',
  },
  {
    id: 119,
    name: 'Браум',
    gender: 'мужской',
    race: 'человек',
    lanes: ['саппорт'],
    regions: ['Фрельйорд'],
    resource: 'мана',
    attackType: 'ближний',
    releaseYear: 2014,
    image:
      'https://ddragon.leagueoflegends.com/cdn/img/champion/tiles/Braum_0.jpg',
  },
  {
    id: 120,
    name: 'Гнар',
    gender: 'мужской',
    race: 'йордл',
    lanes: ['топ'],
    regions: ['Фрельйорд', 'Бандл Сити'],
    resource: 'ярость',
    attackType: ['дальний', 'ближний'],
    releaseYear: 2014,
    image:
      'https://ddragon.leagueoflegends.com/cdn/img/champion/tiles/Gnar_0.jpg',
  },
  {
    id: 121,
    name: 'Азир',
    gender: 'мужской',
    race: 'вознесшийся',
    lanes: ['мид'],
    regions: ['Шурима'],
    resource: 'мана',
    attackType: 'дальний',
    releaseYear: 2014,
    image:
      'https://ddragon.leagueoflegends.com/cdn/img/champion/tiles/Azir_0.jpg',
  },
  {
    id: 122,
    name: 'Калиста',
    gender: 'женский',
    race: 'призрак',
    lanes: ['адк'],
    regions: ['Острова'],
    resource: 'мана',
    attackType: 'дальний',
    releaseYear: 2014,
    image:
      'https://ddragon.leagueoflegends.com/cdn/img/champion/tiles/Kalista_0.jpg',
  },
  {
    id: 123,
    name: "Рек'Сай",
    gender: 'женский',
    race: 'бездна',
    lanes: ['лес'],
    regions: ['Бездна', 'Шурима'],
    resource: 'ярость',
    attackType: 'ближний',
    releaseYear: 2014,
    image:
      'https://ddragon.leagueoflegends.com/cdn/img/champion/tiles/RekSai_0.jpg',
  },
  {
    id: 124,
    name: 'Бард',
    gender: 'мужской',
    race: 'сущность',
    lanes: ['саппорт'],
    regions: ['Рунтерра'],
    resource: 'мана',
    attackType: 'дальний',
    releaseYear: 2015,
    image:
      'https://ddragon.leagueoflegends.com/cdn/img/champion/tiles/Bard_0.jpg',
  },
  {
    id: 125,
    name: 'Экко',
    gender: 'мужской',
    race: 'человек',
    lanes: ['мид', 'лес'],
    regions: ['Заун'],
    resource: 'мана',
    attackType: 'ближний',
    releaseYear: 2015,
    image:
      'https://ddragon.leagueoflegends.com/cdn/img/champion/tiles/Ekko_0.jpg',
  },
  {
    id: 126,
    name: 'Таам Кенч',
    gender: 'мужской',
    race: 'демон',
    lanes: ['саппорт', 'топ'],
    regions: ['Билджвотер', 'Рунтерра'],
    resource: 'мана',
    attackType: 'ближний',
    releaseYear: 2015,
    image:
      'https://ddragon.leagueoflegends.com/cdn/img/champion/tiles/TahmKench_0.jpg',
  },
  {
    id: 127,
    name: 'Киндред',
    gender: 'женский',
    race: 'дух',
    lanes: ['лес'],
    regions: ['Рунтерра'],
    resource: 'мана',
    attackType: 'дальний',
    releaseYear: 2015,
    image:
      'https://ddragon.leagueoflegends.com/cdn/img/champion/tiles/Kindred_0.jpg',
  },
  {
    id: 128,
    name: 'Иллаой',
    gender: 'женский',
    race: 'человек',
    lanes: ['топ'],
    regions: ['Билджвотер'],
    resource: 'мана',
    attackType: 'ближний',
    releaseYear: 2015,
    image:
      'https://ddragon.leagueoflegends.com/cdn/img/champion/tiles/Illaoi_0.jpg',
  },
  {
    id: 129,
    name: 'Джин',
    gender: 'мужской',
    race: 'человек',
    lanes: ['адк'],
    regions: ['Иония'],
    resource: 'мана',
    attackType: 'дальний',
    releaseYear: 2016,
    image:
      'https://ddragon.leagueoflegends.com/cdn/img/champion/tiles/Jhin_0.jpg',
  },
  {
    id: 130,
    name: 'Аурелион Сол',
    gender: 'мужской',
    race: 'дракон',
    lanes: ['мид'],
    regions: ['Таргон', 'Рунтерра'],
    resource: 'мана',
    attackType: 'дальний',
    releaseYear: 2016,
    image:
      'https://ddragon.leagueoflegends.com/cdn/img/champion/tiles/AurelionSol_0.jpg',
  },
  {
    id: 131,
    name: 'Талия',
    gender: 'женский',
    race: 'человек',
    lanes: ['мид', 'лес'],
    regions: ['Шурима'],
    resource: 'мана',
    attackType: 'дальний',
    releaseYear: 2016,
    image:
      'https://ddragon.leagueoflegends.com/cdn/img/champion/tiles/Taliyah_0.jpg',
  },
  {
    id: 132,
    name: 'Клед',
    gender: 'мужской',
    race: 'йордл',
    lanes: ['топ', 'мид'],
    regions: ['Ноксус', 'Бандл Сити'],
    resource: 'ярость',
    attackType: 'ближний',
    releaseYear: 2016,
    image:
      'https://ddragon.leagueoflegends.com/cdn/img/champion/tiles/Kled_0.jpg',
  },
  {
    id: 133,
    name: 'Иверн',
    gender: 'мужской',
    race: 'сущность',
    lanes: ['лес'],
    regions: ['Иония', 'Фрельйорд'],
    resource: 'мана',
    attackType: 'дальний',
    releaseYear: 2016,
    image:
      'https://ddragon.leagueoflegends.com/cdn/img/champion/tiles/Ivern_0.jpg',
  },
  {
    id: 134,
    name: 'Камилла',
    gender: 'женский',
    race: 'человек',
    lanes: ['топ'],
    regions: ['Пилтовер'],
    resource: 'мана',
    attackType: 'ближний',
    releaseYear: 2016,
    image:
      'https://ddragon.leagueoflegends.com/cdn/img/champion/tiles/Camille_0.jpg',
  },
  {
    id: 135,
    name: 'Рэйкан',
    gender: 'мужской',
    race: 'вастайя',
    lanes: ['саппорт'],
    regions: ['Иония'],
    resource: 'мана',
    attackType: 'ближний',
    releaseYear: 2017,
    image:
      'https://ddragon.leagueoflegends.com/cdn/img/champion/tiles/Rakan_0.jpg',
  },
  {
    id: 136,
    name: 'Шая',
    gender: 'женский',
    race: 'вастайя',
    lanes: ['адк'],
    regions: ['Иония'],
    resource: 'мана',
    attackType: 'дальний',
    releaseYear: 2017,
    image:
      'https://ddragon.leagueoflegends.com/cdn/img/champion/tiles/Xayah_0.jpg',
  },
  {
    id: 137,
    name: 'Каин',
    gender: 'мужской',
    race: ['человек', 'даркин'],
    lanes: ['лес'],
    regions: ['Иония', 'Шурима'],
    resource: 'мана',
    attackType: 'ближний',
    releaseYear: 2017,
    image:
      'https://ddragon.leagueoflegends.com/cdn/img/champion/tiles/Kayn_0.jpg',
  },
  {
    id: 138,
    name: 'Орн',
    gender: 'мужской',
    race: 'дух',
    lanes: ['топ'],
    regions: ['Фрельйорд'],
    resource: 'мана',
    attackType: 'ближний',
    releaseYear: 2017,
    image:
      'https://ddragon.leagueoflegends.com/cdn/img/champion/tiles/Ornn_0.jpg',
  },
  {
    id: 139,
    name: 'Зои',
    gender: 'женский',
    race: 'человек',
    lanes: ['мид'],
    regions: ['Таргон'],
    resource: 'мана',
    attackType: 'дальний',
    releaseYear: 2017,
    image:
      'https://ddragon.leagueoflegends.com/cdn/img/champion/tiles/Zoe_0.jpg',
  },
  {
    id: 140,
    name: "Кай'Са",
    gender: 'женский',
    race: 'человек',
    lanes: ['адк'],
    regions: ['Шурима', 'Бездна'],
    resource: 'мана',
    attackType: 'дальний',
    releaseYear: 2018,
    image:
      'https://ddragon.leagueoflegends.com/cdn/img/champion/tiles/Kaisa_0.jpg',
  },
];
