import type { IChampion } from '@/type/championsCard.type';

export const CHAMPIONS: IChampion[] = [
  {
    id: 1,
    name: 'Гарен',
    gender: 'мужской',
    race: 'человек',
    lanes: ['топ'],
    regions: ['Демасия', 'Ноксус'],
    resource: 'без ресурса',
    attackType: 'ближний',
    releaseYear: 2010,
    image:
      'https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Garen_0.jpg',
  },
  {
    id: 2,
    name: 'Дариус',
    gender: 'мужской',
    race: 'человек',
    lanes: ['топ'],
    regions: ['Ноксус'],
    resource: 'мана',
    attackType: 'ближний',
    releaseYear: 2012,
    image:
      'https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Darius_0.jpg',
  },
  {
    id: 3,
    name: 'Фиора',
    gender: 'женский',
    race: 'человек',
    lanes: ['топ'],
    regions: ['Демасия'],
    resource: 'мана',
    attackType: 'ближний',
    releaseYear: 2015,
    image:
      'https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Fiora_0.jpg',
  },
  {
    id: 4,
    name: 'Аатрокс',
    gender: 'мужской',
    race: 'даркин',
    lanes: ['топ'],
    regions: ['Шурима'],
    resource: 'кровь',
    attackType: 'ближний',
    releaseYear: 2013,
    image:
      'https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Aatrox_0.jpg',
  },
  {
    id: 5,
    name: 'Ли Син',
    gender: 'мужской',
    race: 'человек',
    lanes: ['лес'],
    regions: ['Иония'],
    resource: 'энергия',
    attackType: 'ближний',
    releaseYear: 2011,
    image:
      'https://ddragon.leagueoflegends.com/cdn/img/champion/loading/LeeSin_0.jpg',
  },
  {
    id: 6,
    name: 'Кхазикс',
    gender: 'мужской',
    race: 'бездна',
    lanes: ['лес'],
    regions: ['Бездна'],
    resource: 'мана',
    attackType: 'ближний',
    releaseYear: 2012,
    image:
      'https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Khazix_0.jpg',
  },
  {
    id: 7,
    name: 'Элиза',
    gender: 'женский',
    race: 'человек',
    lanes: ['лес'],
    regions: ['Ноксус', 'Острова'],
    resource: 'мана',
    attackType: ['дальний', 'ближний'],
    releaseYear: 2012,
    image:
      'https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Elise_0.jpg',
  },
  {
    id: 8,
    name: 'Вай',
    gender: 'женский',
    race: 'человек',
    lanes: ['лес'],
    regions: ['Пилтовер', 'Заун'],
    resource: 'мана',
    attackType: 'ближний',
    releaseYear: 2012,
    image:
      'https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Vi_0.jpg',
  },
  {
    id: 9,
    name: 'Ари',
    gender: 'женский',
    race: 'вастайя',
    lanes: ['мид'],
    regions: ['Иония'],
    resource: 'мана',
    attackType: 'дальний',
    releaseYear: 2011,
    image:
      'https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Ahri_0.jpg',
  },
  {
    id: 10,
    name: 'Зед',
    gender: 'мужской',
    race: 'человек',
    lanes: ['мид'],
    regions: ['Иония'],
    resource: 'энергия',
    attackType: 'ближний',
    releaseYear: 2012,
    image:
      'https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Zed_0.jpg',
  },
  {
    id: 11,
    name: 'Люкс',
    gender: 'женский',
    race: 'человек',
    lanes: ['мид', 'саппорт'],
    regions: ['Демасия'],
    resource: 'мана',
    attackType: 'дальний',
    releaseYear: 2010,
    image:
      'https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Lux_0.jpg',
  },
  {
    id: 12,
    name: 'Катарина',
    gender: 'женский',
    race: 'человек',
    lanes: ['мид'],
    regions: ['Ноксус'],
    resource: 'без ресурса',
    attackType: 'ближний',
    releaseYear: 2009,
    image:
      'https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Katarina_0.jpg',
  },
  {
    id: 13,
    name: 'Эш',
    gender: 'женский',
    race: 'человек',
    lanes: ['адк'],
    regions: ['Фрельйорд'],
    resource: 'мана',
    attackType: 'дальний',
    releaseYear: 2009,
    image:
      'https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Ashe_0.jpg',
  },
  {
    id: 14,
    name: 'Джинкс',
    gender: 'женский',
    race: 'человек',
    lanes: ['адк'],
    regions: ['Заун'],
    resource: 'мана',
    attackType: 'дальний',
    releaseYear: 2013,
    image:
      'https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Jinx_0.jpg',
  },
  {
    id: 15,
    name: 'Кейтлин',
    gender: 'женский',
    race: 'человек',
    lanes: ['адк'],
    regions: ['Пилтовер'],
    resource: 'мана',
    attackType: 'дальний',
    releaseYear: 2011,
    image:
      'https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Caitlyn_0.jpg',
  },
  {
    id: 16,
    name: 'Вейн',
    gender: 'женский',
    race: 'человек',
    lanes: ['адк', 'топ'],
    regions: ['Демасия'],
    resource: 'мана',
    attackType: 'дальний',
    releaseYear: 2011,
    image:
      'https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Vayne_0.jpg',
  },
  {
    id: 17,
    name: 'Треш',
    gender: 'мужской',
    race: 'призрак',
    lanes: ['саппорт'],
    regions: ['Острова'],
    resource: 'мана',
    attackType: 'ближний',
    releaseYear: 2013,
    image:
      'https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Thresh_0.jpg',
  },
  {
    id: 18,
    name: 'Леона',
    gender: 'женский',
    race: 'человек',
    lanes: ['саппорт'],
    regions: ['Таргон'],
    resource: 'мана',
    attackType: 'ближний',
    releaseYear: 2011,
    image:
      'https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Leona_0.jpg',
  },
  {
    id: 19,
    name: 'Сорака',
    gender: 'женский',
    race: 'сущность',
    lanes: ['саппорт'],
    regions: ['Таргон'],
    resource: 'мана',
    attackType: 'дальний',
    releaseYear: 2009,
    image:
      'https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Soraka_0.jpg',
  },
  {
    id: 20,
    name: 'Нами',
    gender: 'женский',
    race: 'вастайя',
    lanes: ['саппорт'],
    regions: ['Иония'],
    resource: 'мана',
    attackType: 'дальний',
    releaseYear: 2012,
    image:
      'https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Nami_0.jpg',
  },
];
